// Penrose Tiling (P3): the famous aperiodic rhombus tiling, generated by
// golden-ratio subdivision of Robinson half-triangles from a central sun.
// It never repeats, at any scale — five-fold symmetry forbidden to crystals.

import { TAU, samplePalette, mixHex } from '../core/util.js';

const PHI = (1 + Math.sqrt(5)) / 2;

export default {
  id: 'penrose',
  name: 'Penrose Tiling',
  category: 'Geometric',
  description: 'The aperiodic five-fold rhombus tiling, built by golden-ratio subdivision — it never repeats.',
  params: [
    { key: 'levels', label: 'Subdivisions', type: 'range', min: 3, max: 8, step: 1, value: 6 },
    { key: 'zoom', label: 'Zoom', type: 'range', min: 0.8, max: 2.2, step: 0.05, value: 1.15 },
    { key: 'rotation', label: 'Rotation', type: 'range', min: 0, max: 72, step: 1, value: 0 },
    { key: 'contrast', label: 'Tile contrast', type: 'range', min: 0, max: 1, step: 0.05, value: 0.55 },
    { key: 'edgeWidth', label: 'Edge width', type: 'range', min: 0, max: 4, step: 0.25, value: 1 },
    {
      key: 'colorMode', label: 'Color by', type: 'select', value: 'shape',
      options: [
        { value: 'shape', label: 'thick vs thin' },
        { value: 'radial', label: 'radial gradient' },
        { value: 'angle', label: 'angle sweep' },
      ],
    },
  ],

  create({ ctx, width, height, rng, palette, params }) {
    const P = params;
    const cx = width / 2;
    const cy = height / 2;

    // triangles as [color, ax, ay, bx, by, cx2, cy2]; color 0 = half-thick, 1 = half-thin
    function subdivide(tris) {
      const out = [];
      for (const [c, ax, ay, bx, by, cx2, cy2] of tris) {
        if (c === 0) {
          const px = ax + (bx - ax) / PHI;
          const py = ay + (by - ay) / PHI;
          out.push([0, cx2, cy2, px, py, bx, by], [1, px, py, cx2, cy2, ax, ay]);
        } else {
          const qx = bx + (ax - bx) / PHI;
          const qy = by + (ay - by) / PHI;
          const rx = bx + (cx2 - bx) / PHI;
          const ry = by + (cy2 - by) / PHI;
          out.push([1, rx, ry, cx2, cy2, ax, ay], [1, qx, qy, rx, ry, bx, by], [0, rx, ry, qx, qy, ax, ay]);
        }
      }
      return out;
    }

    let drawn = false;
    return {
      frame() {
        if (drawn) return false;
        drawn = true;
        ctx.fillStyle = palette.bg;
        ctx.fillRect(0, 0, width, height);

        // wheel of 10 half-thick triangles around the centre ("sun" start)
        const R = Math.hypot(width, height) * 0.58 * P.zoom;
        const rot = (P.rotation * Math.PI) / 180;
        let tris = [];
        for (let i = 0; i < 10; i++) {
          let a1 = ((2 * i - 1) * Math.PI) / 10 + rot;
          let a2 = ((2 * i + 1) * Math.PI) / 10 + rot;
          if (i % 2 === 0) [a1, a2] = [a2, a1]; // mirror alternate slices
          tris.push([0, cx, cy, cx + Math.cos(a1) * R, cy + Math.sin(a1) * R, cx + Math.cos(a2) * R, cy + Math.sin(a2) * R]);
        }
        for (let l = 0; l < P.levels && tris.length < 90000; l++) tris = subdivide(tris);

        const maxR = R;
        ctx.lineJoin = 'round';
        for (const [c, ax, ay, bx, by, cx2, cy2] of tris) {
          const mx = (ax + bx + cx2) / 3;
          const my = (ay + by + cy2) / 3;
          let t;
          if (P.colorMode === 'radial') t = Math.hypot(mx - cx, my - cy) / (maxR * 0.7);
          else if (P.colorMode === 'angle') t = (Math.atan2(my - cy, mx - cx) + Math.PI) / TAU;
          else t = c === 0 ? 0.25 : 0.75;
          let fill = samplePalette(palette.colors, Math.min(1, t));
          // pull the two shapes apart tonally, plus a whisper of per-tile variance
          if (P.colorMode !== 'shape') {
            fill = mixHex(fill, c === 0 ? '#ffffff' : '#000000', P.contrast * 0.18);
          }
          // per-rhombus (not per-half-triangle) tone: hash the shared B–C edge
          // midpoint so both halves of a rhombus land on the same tint
          const h = Math.abs(Math.sin((bx + cx2) * 12.9898 + (by + cy2) * 78.233) * 43758.5453) % 1;
          fill = mixHex(fill, palette.bg, (1 - P.contrast) * 0.25 * h);
          ctx.fillStyle = fill;
          ctx.beginPath();
          ctx.moveTo(ax, ay);
          ctx.lineTo(bx, by);
          ctx.lineTo(cx2, cy2);
          ctx.closePath();
          ctx.fill();
          if (P.edgeWidth > 0) {
            // stroke only the rhombus outline edges (C–A and A–B), never the
            // B–C seam where the two half-triangles meet
            ctx.strokeStyle = palette.bg;
            ctx.lineWidth = P.edgeWidth;
            ctx.beginPath();
            ctx.moveTo(cx2, cy2);
            ctx.lineTo(ax, ay);
            ctx.lineTo(bx, by);
            ctx.stroke();
          }
        }
        return false;
      },
    };
  },
};
